- houssg/index.html
- houssg/src/App.css
- houssg/src/App.tsx
- houssg/src/assets/styles/theme.ts
- houssg/src/hooks/useDebounce.ts
- houssg/src/hooks/usePathname.ts
- houssg/src/layout/Footer.tsx
- houssg/src/layout/Header.tsx
- houssg/src/layout/Nav.tsx
- houssg/src/layout/index.ts
- houssg/src/pages/Main.tsx
- houssg/src/pages/OwernerHome.tsx
- houssg/src/pages/OwnerAuth.tsx
- houssg/src/pages/UserHome.tsx
- houssg/src/pages/UserHouseList.tsx
- houssg/src/pages/UserMain.tsx
- houssg/src/pages/UserMypage.tsx
- houssg/src/pages/UserReservationList.tsx
- 레이아웃 및 커스텀 훅 생성
- router 가이드라인 등록, user layout 생성,  debounce및 path 훅 만들기
- #7
> 7 layout -  router 가이드라인 등록, user layout 생성,  debounce및 path 훅 만들기

- houssg/package-lock.json
- houssg/src/api/api.ts
- houssg/src/components/auth/Login.tsx
- houssg/src/components/auth/SignUp.tsx
- houssg/src/components/common/CommonModal.tsx
- houssg/src/hooks/useReduxToolkit.ts
- houssg/src/layout/Header.tsx
- houssg/src/pages/user/UserHome.tsx
- houssg/src/store/redux/index.ts
- houssg/src/store/redux/modalSlice.ts
- 공용 컴퍼넌트 모달 생성
- 공용 컴퍼넌트 모달 생성
- 모달 관리 스테이트 전역 변수화
- #10
> [✨ ]Feagure/10 modal 모달 공용 컴퍼넌트 생성

- houssg/src/components/auth/AuthWrap.tsx
- houssg/src/components/auth/Login.tsx
- houssg/src/components/auth/SignUp.tsx
- houssg/src/components/auth/index.ts
- houssg/src/components/common/CommonModal.tsx
- houssg/src/layout/Header.tsx
- houssg/src/layout/Nav.tsx
- houssg/src/store/redux/modalSlice.ts
-   모달 에러 수정 styledcomponent 사용법관련 코드 수정
-  모달 호출 방식 변경 ,styledcomponents props수정
- #16
> Figure/16 auth UI 모달 에러 수정 styledcomponent 사용법관련 코드 수정

- houssg/src/pages/user/UserHome.tsx
- 푸터가 내부 컴퍼넌트와 겹치는 버그 수정
- 푸터 겹치지 않게 div추가
- 푸터 겹치지 않게 div추가
- #18
> :bug:  푸터가 내부 컴퍼넌트와 겹치는 버그 수정

- houssg/.gitignore
- houssg/src/api/api.ts
- houssg/src/assets/constant/auth.ts
- houssg/src/assets/constant/index.ts
- houssg/src/assets/constant/regSignUp.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/auth/Login.tsx
- houssg/src/components/auth/SignUp.tsx
- houssg/src/components/auth/element/AuthInput.tsx
- houssg/src/components/auth/element/index.ts
- houssg/src/components/auth/index.ts
- houssg/src/components/common/CommonModal.tsx
- houssg/src/hooks/useDebounce.ts
- houssg/src/layout/Nav.tsx
- houssg/src/pages/owner/OwnerAuth.tsx
- houssg/src/types/auth/index.ts
- houssg/src/utils/authFunction.ts
- houssg/src/utils/index.ts
- 로그인 및 회원관리 axios 요청 및 유효성 검사
- 로그인 및 회원관리 axios 요청 및 유효성 검사
- 디바운스 및 memo를 통해서 랜더링 관리
- 모달 닫힐 떄 내부 컴퍼넌트 언마운트하기
- #34
> [✨ ]Feature/34  로그인 및 회원관리 axios 요청 및 유효성 검사

- houssg/src/assets/icons/index.ts
- houssg/src/components/CancelReservation.tsx
- houssg/src/components/ReservationList.tsx
- houssg/src/components/common/CommonModal.tsx
- houssg/src/pages/user/UserReservationList.tsx
- ReservationList 페이지 내 예약상태창 UI
- ReservationList 페이지 내 예약상태창 UI 및 예약취소 모달 적용
- #32
> [💄] Feature/32 reservationstate ReservationList 페이지 내 예약상태창 UIli

- houssg/src/api/api.ts
- houssg/src/components/auth/AuthWrap.tsx
- houssg/src/components/common/CommonModal.tsx
- 개요
- [🐛 ] Feature/39 fixmodal 모달 회원가입 툴팁 남는 오류 수정
- #39
> [🐛 ] Feature/39 fixmodal 모달 회원가입 툴팁 남는 오류 수정

- houssg/src/App.tsx
- houssg/src/components/BriefHouse.tsx
- houssg/src/components/common/HomeSlider.tsx
- houssg/src/components/common/TabMenu.tsx
- houssg/src/components/house/HouseInfo.tsx
- houssg/src/components/house/HouseReview.tsx
- houssg/src/components/house/RoomList.tsx
- houssg/src/pages/user/UserHouseDetail.tsx
- houssg/src/pages/user/UserHouseList.tsx
- 개요
- 숙소 상세 페이지 UI 레이아웃 구현
- 없음
- #36
> 💄Feature/36 숙소 상세 페이지 UI - 레이아웃 구현

- houssg/src/api/index.ts
- houssg/src/api/kakao.ts
- houssg/src/components/auth/Login.tsx
- houssg/src/components/auth/element/AuthInput.tsx
- houssg/src/hooks/useKaKaoLogin.ts
- houssg/src/pages/user/UserMain.tsx
- houssg/src/utils/authFunction.ts
카카오 로그인 초안 및 코드받기
- 카카오 로그인 초안
카카오디벨로퍼 등록 및 api키 등록
env를 이용한 api키 관리
code값을 확인하는 useKakaoLogin 훅 생성
UserMain 컴퍼넌트에서 code 여부 확인
카카오 , visibility 이미지 styled 컴퍼넌트화
- #44
> :sparkles: 카카오 로그인 초안 및 코드받기

- houssg/src/components/BannerSlider.tsx
- houssg/src/components/BriefHouse.tsx
- houssg/src/components/CancelReservation.tsx
- houssg/src/components/HomeSlider.tsx
- houssg/src/components/ReservationCollapseDetail.tsx
- houssg/src/components/ReservationList.tsx
- houssg/src/pages/user/UserMain.tsx
- houssg/src/pages/user/UserReservationList.tsx
- houssg/src/store/redux/ReservationDetailSlice.ts
- 유저 예약내역페이지
- 유저 예약내역페이지 예약상태창 수정
- 전체적인 UI, 예약상태에 따라 출력될 글자 변경, 예약취소 모달 UI 수정, onClick시 모달 종료 및 alert(추후 예약취소 기능구현)
- #41
> [💄] Feature/41 reservation update 유저 예약내역페이지 예약상태창 수정

- houssg/src/App.tsx
- houssg/src/assets/styles/theme.ts
- houssg/src/layout/Nav.tsx
- houssg/src/pages/owner/OwnerRegister.tsx
- houssg/src/pages/owner/OwnerReservation.tsx
- houssg/src/pages/owner/index.ts
theme추가 및 nav 이름 수정
- Theme추가 및 nav 이름 수정
- Theme추가 및 nav 이름 수정
- #50
> :recycle: Theme추가 및 nav 이름 수정

- houssg/src/components/house/HouseDescription.tsx
- houssg/src/pages/user/UserHouseDetail.tsx
- 개요
- 숙소 상세 페이지 상단 컴포넌트 HouseInfo로 파일 생성
- 하단 탭 중 숙소 소개 컴포넌트 파일명을 HouseInfo-> HouseDescription으로 수정
- #42
> Feature/36 숙소 상세 페이지 컴포넌트 파일명 수정

- houssg/src/components/house/HouseDescription.tsx
좌측 정렬, 줄 바꿈 css
- 개요
- 숙소 소개 UI
- 없음
- #54
> [💄 ] 숙소 상세 페이지 - 숙소 소개 UI

- houssg/src/api/api.ts
- houssg/src/assets/constant/auth.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/auth/Login.tsx
- houssg/src/components/auth/SignUp.tsx
- houssg/src/hooks/index.ts
- houssg/src/utils/authFunction.ts
- houssg/src/utils/index.ts
- 로그인 회원가입 관련 서버와 연결 확인
- 서버와 연결 확인
- authfunction export 변경
- #46
> [✨ ]Feature/46 auth function

- houssg/package-lock.json
- houssg/src/assets/constant/reservationDummy.ts
- houssg/src/components/common/index.ts
- houssg/src/components/owner/management/ManageReview.tsx
- houssg/src/components/owner/management/ManageRoomWrap.tsx
- houssg/src/components/owner/management/ManageTabComp.tsx
- houssg/src/components/owner/management/element/RoomCompEdit.tsx
- houssg/src/components/owner/management/element/RoomCompRead.tsx
- houssg/src/components/owner/management/element/RoomCompToggler.tsx
- houssg/src/components/owner/management/element/RoomReviewComp.tsx
- houssg/src/layout/index.ts
- houssg/src/types/index.ts
- houssg/src/types/manage.ts
- houssg/src/utils/authFunction.ts
- 사업자 페이지 객실관리 및 리뷰 러프 디자인
- 사업자 페이지 객실관리 및 리뷰 러프 디자인
- #61
> [💄 ] Feature/61 ownerroomreviewui  사업자 페이지 객실관리 및 리뷰 러프 디자인

- houssg/src/components/common/CommonInstruction.tsx
- houssg/src/components/common/CommonModal.tsx
- houssg/src/components/common/index.ts
- houssg/src/components/reservation/ReservationList.tsx
- houssg/src/components/usermypages/MyPage.tsx
- houssg/src/store/redux/modalSlice.ts
- CommonInstructino이 불필요하게 많이 호출되지 않도록 리팩토링
- CommonInstruction 및 모달 리팩토링
- modalSlice, CommonModal, CommonInstruction , 예약취소, 쿠폰등록 관련 코드 수정
- #70
> [♻️ ]Feature/70 modal refactoring 모달 및 안내문 리팩토링

- houssg/src/components/house/HouseInfo.tsx
- 개요
- 작업사항
- 입퇴실 시간, 시설 및 서비스 아이콘 추가
- #72
> Feature/72 숙소 상세 페이지 - 숙소 정보 UI 수정

- houssg/.dockerignore
- houssg/Dockerfile
- houssg/package.json
- houssg/src/components/house/BriefHouse.tsx
- houssg/src/components/house/HouseDescription.tsx
- houssg/src/components/house/HouseReview.tsx
- houssg/src/pages/owner/OwnerHouseRegister.tsx
- houssg/vite.config.ts
- 로컬 환경에서 도커 container에서 앱실행하기
-  도커 file packagejson, vite.config 설정
- 도커 file packagejson, vite.config 설정
- #66
> [✨ ] Feature/66 docker 로컬환경 도커 container 생성

- houssg/package-lock.json
- houssg/package.json
- houssg/src/App.css
- houssg/src/assets/constant/reservationDummy.ts
- houssg/src/components/common/CommonCalendar.css
- houssg/src/components/common/CommonCalendar.tsx
- houssg/src/components/common/index.ts
- houssg/src/hooks/useCalendarStyle.ts
- houssg/src/pages/owner/OwnerReservation.tsx
- houssg/src/types/common.ts
- houssg/src/types/index.ts
- 공용 컴퍼넌트 달력
- Fullcalendar로 달력생성
- 달력에 조건부 색주는 훅 생성(추후보완)
- 달력 날짜 클릭시 함수
- 
- #77
> Feature/77 calendar 공용컴퍼넌트 달력 만들기

- houssg/src/assets/constant/reservationDummy.ts
- houssg/src/components/common/CommonCalendar.tsx
- houssg/src/components/owner/reservation/ReservationDropDown.tsx
- houssg/src/components/owner/reservation/index.ts
- houssg/src/pages/owner/OwnerReservation.tsx
달력 스타일 업데이트 + 드롭다운추가
- 달력 스타일 업데이트 + 드롭다운추가
- 달력 스타일 업데이트 + 드롭다운추가
- 달력 수정
- #80
> :sparkles: 달력 스타일 업데이트 + 드롭다운추가

- houssg/index.html
- houssg/package-lock.json
- houssg/package.json
- houssg/src/App.tsx
- houssg/src/components/common/KakaoMap.tsx
- houssg/src/components/owner/register/AddressFinder.tsx
- houssg/src/components/owner/register/index.tsx
- houssg/src/pages/owner/OwnerHouseRegister.tsx
- houssg/src/pages/owner/OwnerManagement.tsx
- package-lock.json
- 지도와 우편번호 추가 
- daum-post 라이브러리 추가
- 마커 추가
- #78
> [✨ ] Feature/78 maponlyaddress  지도와 우편번호 추가

- .github/workflows/cicd.yml
- houssg/.dockerignore
- houssg/Dockerfile
- houssg/Dockerfile.prod
-  깃액션 생성 (aws ec2 미수정)
- gitaction 용  cicd.yml 생성
- #85 
close #85
> [📝 ]  Feature/85 gitactionfirst 깃액션 생성 (aws ec2 미수정)

- .github/workflows/cicd.yml
YML파일 AWS부분 반영
- cicd 파이프라인 완성
- YML파일 AWS부분 반영
- YML파일 AWS부분 반영
- #90 
close #90
> :memo: YML파일 AWS부분 반영

- houssg/src/components/usermypages/EditPassword.tsx
- 유저 마이페이지 '나의 정보'
- 유저 마이페이지 '나의 정보' 비밀번호 수정 모달 작업
- 유저 마이페이지 '나의 정보' 비밀번호 수정 모달 코드 개선
- #97 
close #97
> [🐛]Feature/97 edit password code update 유저 마이페이지 '나의 정보' 비밀번호 수정 모달 작업

- .github/workflows/cicd.yml
yml파일 오류로 인한 버그 수정
- yml파일 오류로 인한 버그 수정
-  uses 버전업, checkout 경로 수정
- #103 
close #103
> :bug: Yml파일 오류로 인한 버그 수정

- houssg/.dockerignore
- houssg/src/components/house/HouseReview.tsx
e 타입 미지정에 의한 오류 수정
- e 타입 미지정에 의한 오류 수정
- e 타입 미지정에 의한 오류 수정
- #105 
close #105
> :bug: E 타입 미지정에 의한 오류 수정

- .github/workflows/cicd.yml
- houssg/.dockerignore
- houssg/src/assets/styles/GlobalStyle.ts
gitaction 및 인풋 수정
-  gitaction ssh 부분 password 대신 key 사용, input edge에만 적용되는 ms-reveal 제거
-  gitaction ssh 부분 password 대신 key 사용, input edge에만 적용되는 ms-reveal 제거
- #107 
close #107
> :bug: Gitaction 및 인풋 수정

- .github/workflows/cicd.yml
> :bug: 깃액션 오류 수정 -2 

- .github/workflows/cicd.yml
포트포워딩 오류 수정
- 포트포워딩 오류 수정
- 포트포워딩 오류 수정
- #107
> :bug: 포트포워딩 오류 수정

- houssg/src/components/common/CommonCalendar.tsx
- houssg/src/hooks/useCalendarStyle.ts
타입명에 의한 임포트 오류 해결
-  타입명에 의한 임포트 오류 해결
- 달력부분 import 오류 수정
- #115 
close #115
> :bug:  타입명에 의한 임포트 오류 해결

- houssg/src/components/common/CommonModal.tsx
- houssg/src/components/common/Rating.tsx
- houssg/src/components/house/BriefHouse.tsx
- houssg/src/components/house/HouseInfo.tsx
- houssg/src/components/house/HouseReview.tsx
- houssg/src/components/house/Review.tsx
- houssg/src/components/reservation/Provision.tsx
- houssg/src/components/usermain/HomeSlider.tsx
- houssg/src/pages/user/UserHouseList.tsx
- 개요
- 리팩토링
- commit으로 확인 바람
- #117
close #117
> ♻️ Feature/117 리팩토링

- houssg/src/components/house/HouseReview.tsx
- 개요
- 후기 작성 시 글자수 제한 ( 리뷰 목록 ...은 안 해도 될 듯 )
- 변경사항
- #119 
close #119
> :sparkles: 숙소 상세 페이지 - 리뷰 탭 - 리뷰 입력 글자수 제한

- houssg/src/components/common/TabMenu.tsx
- houssg/src/components/house/HouseInfo.tsx
- houssg/src/components/house/HouseReview.tsx
- houssg/src/components/house/RoomDetail.tsx
- houssg/src/components/reservation/Provision.tsx
- houssg/src/pages/user/UserHouseList.tsx
- 개요
- css 추가
- 없음
- #121
close #121
> 💄 Feature/121 review hover

- houssg/package-lock.json
- houssg/package.json
- houssg/src/index.tsx
리액트쿼리 설치, 리액트 쿼리 개발자도구 설치
- 리액트 쿼리 등록, 리액트 쿼리 개발자 도구 설치
- #122 
close #122
> :sparkles: 리액트쿼리 설치, 리액트 쿼리 개발자도구 설치

- houssg/src/App.css
- houssg/src/assets/styles/StyledComponents.ts
- houssg/src/assets/styles/index.ts
- houssg/src/components/auth/AuthWrap.tsx
- houssg/src/components/auth/FindId.tsx
- houssg/src/components/auth/FindPw.tsx
- houssg/src/components/auth/Login.tsx
- houssg/src/components/auth/PwChangeForm.tsx
- houssg/src/components/auth/PwPermitForm.tsx
- houssg/src/components/auth/SignUp.tsx
- houssg/src/components/auth/element/AuthInput.tsx
- houssg/src/components/auth/element/AuthModeBtn.tsx
- houssg/src/components/auth/element/AuthSubmitBtn.tsx
- houssg/src/components/auth/index.ts
- houssg/src/components/common/CommonInstruction.tsx
- houssg/src/types/auth.ts
- houssg/src/types/index.ts
- houssg/src/utils/authFunction.ts
- 로그인 및 회원가입 기능 UI 추가 아이디 찾기 비밀번호 찾기 휴대전화 인증UI
- 로그인 및 회원가입 기능 UI 추가 아이디 찾기 비밀번호 찾기 휴대전화 인증UI
- 로그인 변경, styleComponents 관련 일부 스타일 수정 및  공용화
- #134 
close #134
> [💄 ] Feature/134 doauth UI  로그인 및 회원가입 기능 UI 추가 아이디 찾기 비밀번호 찾기 휴대전화 인증UI

- houssg/src/App.tsx
- houssg/src/assets/constant/routingPath.ts
- houssg/src/components/owner/management/ManageNav.tsx
- houssg/src/components/owner/management/ManageRoomWrap.tsx
- houssg/src/pages/owner/OwnerRoomRegister.tsx
- houssg/src/pages/owner/index.ts
- 객실 등록 라이터 등록+ 숙소 하단탭 색 버그 수정
-  1 객실 추가하기
- 내 숙소 하단 객실 정보 리뷰확인 색깔 변경
- #144 
close #144
> :sparkles: 객실 등록 라이터 등록+ 숙소 하단탭 색 버그 수정

- houssg/package-lock.json
- houssg/package.json
- houssg/src/pages/owner/OwnerIncome.tsx
- 개요
- 정산 내역 UI
- 없음
- #141 
close #141
> Feature/141정산 내역 UI

- houssg/src/pages/user/UserMain.tsx
env 확인용 주석 추가
- env 확인용 주석 추가
- #150
> [🧪 ] Env 확인용 주석 추가

- houssg/src/assets/styles/StyledComponents.ts
- houssg/src/assets/styles/index.ts
- houssg/src/components/common/ImageUploader.tsx
- houssg/src/components/common/RoomImgSlider.tsx
- houssg/src/components/common/index.ts
- houssg/src/pages/owner/OwnerRoomRegister.tsx
- houssg/src/pages/user/UserMain.tsx
- houssg/src/types/common.ts
- houssg/src/types/index.ts
- 객실 업로드에 필요한 swiper와 업로드 기능 구현
- 객실 업로드에 필요한 swiper와 업로드 기능 구현
- #146  의 TODO 체크
- #146 
close #146
> [✨ ] Feature/146 room regi UI  객실 업로드에 필요한 swiper와 업로드 기능 구현

- .github/workflows/cicd.yml
gitaction 수정
- 개요
- gitaction env 위치 수정
- #152 
close #152
> :construction_worker: Gitaction 수정  gitaction env 위치 수정

- .github/workflows/cicd.yml
- houssg/src/assets/constant/urlConst.ts
- houssg/src/helper/authFunction.ts
-  uri 테스트
- test
- #152 
close #152
> [🧪]  Feature/152 fixenv2 test용

- houssg/src/assets/icons/index.ts
풀리퀘 오류해결
- build 오류 해결
- icon에서 Icon으로 소문자를 대문자로 변경
- #163
> [🐛]  풀리퀘 오류해결

- houssg/src/assets/constant/urlConst.ts
백엔드 uri 명명법 변경에 따른 수정
- 백엔드 uri 명명법 변경에 따른 수정
- 백엔드 uri 명명법 변경에 따른 수정
- #186 
close #186
> [:ambulance: ] feature/186 백엔드 uri 명명법 변경에 따른 수정

- houssg/src/assets/styles/index.ts
- houssg/src/assets/styles/size.ts
- houssg/src/components/owner/management/ManageHouseEdit.tsx
- houssg/src/components/owner/management/ManageHouseRead.tsx
- houssg/src/components/owner/management/ManageWrapComp.tsx
- houssg/src/hooks/index.ts
- houssg/src/hooks/useCalWindowWidth.ts
- houssg/src/hooks/useImageConverter.ts
- houssg/src/utils/index.ts
- houssg/src/utils/utilFunction.ts
- 숙소 정보 업데이트 값 query로 받기, 이미지 파일 전송 가능하도록 수정, 화면 크기 구하는 훅 생성
1 query로 숙소 정보 수정 페이지 정보 받아오기
2 uploader 컴퍼넌트로 이미지 수정 반영
3 화면 크기 구해주는 훅 및 이를 바탕으로 업로더 크기 반응형 적용
- #192 
close #192
> [✨ ]Feature/192 house edit 숙소 정보 업데이트 값 query로 받기, 이미지 파일 전송 가능하도록 수정, 화면 크기 구하는 훅 생성

- houssg/src/components/common/ImageUploader.tsx
- houssg/src/components/owner/management/ManageHouseEdit.tsx
- houssg/src/components/owner/management/ManageWrapComp.tsx
- houssg/src/hooks/useImageConverter.ts
- houssg/src/types/common.ts
- houssg/src/utils/index.ts
- houssg/src/utils/utilFunction.ts
- 업로더에 base64를  파일로 만드는 디코더 유틸함수 추가
- 업로더에 base64를  파일로 만드는 디코더  유틸함수 추가
- #195 
close #195
> [✨ ]Feature/195 uploader refac 업로더에 base64를  파일로 만드는 디코더 유틸함수 추가

- houssg/src/assets/constant/urlConst.ts
- houssg/src/pages/user/UserHouseList.tsx
- houssg/src/types/house.ts
- 유저 숙소 목록 페이지 오류 수정
- 유저 숙소 목록 페이지 api 요청
- #202 
close #202
> [🚑] 유저 숙소 목록 페이지 오류 수정

- houssg/src/assets/constant/routingPath.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/common/HeartIcons.tsx
- houssg/src/components/house/HouseInfo.tsx
- 개요
- 좋아요컴포넌트 백연동
- 변경사항
- #200
close #200
> 💄 Feature/200 좋아요 컴포넌트 백연동

- houssg/src/pages/user/UserHouseList.tsx
- 빌드오류수정
- 빌드오류수정
- #205 
close #205
> [🚑] Feature/205 빌드오류수정

- houssg/src/assets/styles/StyledComponents.ts
- houssg/src/components/owner/management/ManageHouseRead.tsx
- houssg/src/components/owner/register/HouseImageRegi.tsx
- houssg/src/components/owner/register/HouseInfoRegi.tsx
- houssg/src/components/owner/register/element/StepMover.tsx
- houssg/src/pages/owner/OwnerHouseRegister.tsx
- houssg/src/types/index.ts
- houssg/src/types/regi.ts
- 파일형태로 이미지 전송하도록 리팩토링 및 빌드에러 수정
- 함수로 요청까지,  이미지 업로더 리팩토링에 따른 빌드에러 픽스
- #208  #198 
close #208 
close #198
> [♻️ ]  파일형태로 이미지 전송하도록 리팩토링 및 빌드에러 수정

- houssg/src/components/usermypages/MyFavorite.tsx
- 유저 마이페이지 favorite 빌드 오류 수정
- 유저 마이페이지 favorite 빌드 오류 수정
- #211 
close #211
> [🚑] Feature/211 빌드오류마이페이지

- houssg/src/components/owner/register/BusinessRegi.tsx
- houssg/src/components/owner/register/HouseInfoRegi.tsx
- houssg/src/components/owner/register/element/StepMover.tsx
- houssg/src/helper/index.ts
- houssg/src/helper/ownerFunction.ts
- houssg/src/hooks/useImageConverter.ts
- houssg/src/pages/owner/OwnerHouseRegister.tsx
- mutation을 이용한 업로드 및 invalidatequeries로 내숙소 정보 다시 받기
- mutation을 이용한 업로드 및 invalidatequeries로 내숙소 정보 다시 받기
- 이슈번호
> [✨ ] Feature/213 regihousemutation mutation을 이용한 업로드 및 invalidatequeries로 내숙소 정보 다시 받기

- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/owner/management/ManageHouseEdit.tsx
- houssg/src/components/owner/register/element/StepMover.tsx
- houssg/src/helper/ownerFunction.ts
- houssg/src/types/index.ts
- houssg/src/types/manage.ts
뮤테이션을 통해서 수정 기능 구현
- 뮤테이션을 통해서 수정 기능 구현
- 뮤테이션을 통해서 수정 기능 구현
- 타입 변수 나누기
-  뮤테이션에 실행할 함수 추가
-  수정 조건 분기 ( 수정된 내용 없을 때, 수정취소 되도록)
- #215 
close #215
> [✨ ] 뮤테이션을 통해서 수정 기능 구현 -- >추후 백엔드 디버깅 후 재확인

- houssg/src/components/owner/management/ManageHouseEdit.tsx
- houssg/src/helper/ownerFunction.ts
- houssg/src/types/manage.ts
숙소 수정 기능 작동 (추후 : 이미지파일 보내기)
숙소 수정 기능 작동 (추후 : 이미지파일 보내기)
- 숙소번호 blob에 추가 전송, 서비스 전송
- #218 
close #218
> [:bug: ]숙소 수정 기능 작동 (추후 : 이미지파일 보내기)

- houssg/src/assets/constant/index.ts
- houssg/src/assets/constant/listData.ts
- houssg/src/assets/constant/queryKey.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/owner/management/ManageHouseRead.tsx
- houssg/src/components/owner/management/ManageRoomWrap.tsx
- houssg/src/components/owner/management/ManageTabComp.tsx
- houssg/src/components/owner/management/element/RoomCompEdit.tsx
- houssg/src/components/owner/management/element/RoomCompRead.tsx
- houssg/src/components/owner/management/element/RoomCompToggler.tsx
- houssg/src/helper/index.ts
- houssg/src/helper/roomFunction.ts
- houssg/src/types/index.ts
- houssg/src/types/manage.ts
- houssg/src/types/room.ts
- react query를 통해서 객실 데이터 받기+  manage에서 관리하던 room데이터 room에서 관리하도록 리팩토링
- react query를 통해서 객실 데이터 받기
-  manage에서 관리하던 room데이터 room에서 관리하도록 리팩토링
- url, queryKey, roomFunc 추가하기
- manage에서 관리하던 타입 및 값들 room에서 관리하기
- #219 
clsoe #219
> [✨ ]Feature/219 getroomdata react query를 통해서 객실 데이터 받기+  manage에서 관리하던 room데이터 room에서 관리하도록 리팩토링

- houssg/src/components/owner/management/ManageRoomWrap.tsx
- houssg/src/components/owner/management/ManageWrapComp.tsx
- houssg/src/components/owner/management/element/RoomCompRead.tsx
- houssg/src/components/owner/register/element/StepMover.tsx
- houssg/src/helper/index.ts
- houssg/src/helper/roomFunction.ts
- houssg/src/pages/owner/OwnerRoomRegister.tsx
- houssg/src/pages/user/UserHouseList.tsx
- houssg/src/types/index.ts
- houssg/src/types/manage.ts
- houssg/src/types/room.ts
- 개요
1 백엔드에게 이미지 정상적으로 전송되는 지 확인
2 객실 이미지 값 넣기
3 객실 등록하기 mutation 으로 구현
4 room 빈배열이 들어올 경우 등록된 방이 없다고 알리기
5 mutation 전에 등록가능여부 검사
6 api 키 바뀐거 수정 ( 숙소 get부분)
-  검색 부분에 전체데이터 받는 부분 api 수정사항 반영
- close #226
> [✨ ] Feature/226 roomregi+debugging  객실 등록하기 api 연결 및 기능 구현 +이미지 관련 api 확인 및 수정

- houssg/src/App.tsx
- houssg/src/assets/constant/routingPath.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/house/BriefHouse.tsx
- houssg/src/components/house/HouseDescription.tsx
- houssg/src/components/house/HouseInfo.tsx
- houssg/src/components/house/HouseReview.tsx
- houssg/src/components/house/Review.tsx
- houssg/src/components/house/RoomDetail.tsx
- houssg/src/components/house/RoomList.tsx
- houssg/src/pages/user/UserHouseDetail.tsx
- houssg/src/pages/user/UserMain.tsx
- houssg/src/types/houseDetailPage.ts
- houssg/src/types/index.ts
- 개요
- 작업사항
- 숙소 상세 페이지 첫화면 데이터 숙소 상세 페이지에서 api 통신으로 받기,
타페이지에서 숙소 상세 페이지로 이동시 숙소 데이터가 아닌 숙소 넘버 전달 ( feat.useParams )
- #224 
close #224
> 💄 Feature/224 유저 숙소상세페이지 첫화면api연동

- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/auth/element/AuthInput.tsx
- houssg/src/components/auth/index.ts
- houssg/src/components/owner/register/BusinessRegi.tsx
- houssg/src/types/regi.ts
- 네이버클라우드 ocr 관련 API  구현,
1 OCR API 확인
2 사업자 등록 부분 UI 수정
3 사업자 등록 로딩처리
- Auth인풋 디바운스 간격 조절
- close #232
> [✨ ] Feature/232 ocrapi 네이버클라우드 ocr 관련 API  구현,  (숙소등록)사업자등록 유아이

- houssg/src/components/owner/management/element/RoomCompEdit.tsx
- houssg/src/components/owner/management/element/RoomCompRead.tsx
- houssg/src/helper/index.ts
- houssg/src/helper/roomFunction.ts
- houssg/src/hooks/index.ts
- houssg/src/hooks/useFocusRef.ts
- houssg/src/pages/owner/OwnerRoomRegister.tsx
- houssg/src/types/room.ts
-  객실 수정하기 구현
TODO : 스와이퍼크기 반응형 + 백엔드에서 수정 로직 변경후 api 연결 test
- 내 객실 정보에서 객실 이미지 swiper로 보여주기
- 객실 수정하기 mutation으로 api 연결
- 객실 수정하기 로직 변경에 따른 기존 이미지 수정 여부 처리
- 객실 이미지 요청전에 수정 내용없으면 api 미호출
- 객실 수정시 빈값이 있는 경우 처리
-   화면 focus 커스텀훅 생성 https://ungumungum.tistory.com/51
- 자잘한 UI fix
- close #231
> [✨ ] Feature/231 roomupdate 객실 수정하기 구현 + ui 작업

- .github/workflows/cicd.yml
- houssg/Dockerfile.prod
- houssg/nginx.conf
- houssg/src/components/house/RoomDetail.tsx
- houssg/src/components/house/RoomList.tsx
- houssg/src/components/owner/management/element/RoomCompRead.tsx
- nginx spa에 의한 router에러 및 빌드에러 수정
- nginx spa에 의한 router에러 해결 -> nginx.conf 파일에서         try_files $uri $uri/ /index.html;
- 도커파일에서 해당 내용 반영 nginx 빌드시 반영
- RoomData 형식에 맞게 슬라이더 사용  
- 컴퍼넌트의 export 문 export defauilt 로 수정
- close #235
> [🐛 ] Feature/235 fixnginx nbuild nginx spa에 의한 router에러 및 빌드에러 수정

- houssg/src/api/index.ts
- houssg/src/assets/constant/queryKey.ts
- houssg/src/assets/constant/reservationDummy.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/house/RoomList.tsx
- houssg/src/components/owner/management/ManageHouseEdit.tsx
- houssg/src/components/owner/management/ManageNav.tsx
- houssg/src/components/owner/management/ManageReview.tsx
- houssg/src/components/owner/management/ManageTabComp.tsx
- houssg/src/components/owner/management/element/DeclarationReview.tsx
- houssg/src/components/owner/management/element/HouseComment.tsx
- houssg/src/components/owner/management/element/RoomCompEdit.tsx
- houssg/src/components/owner/management/element/RoomReviewComp.tsx
- houssg/src/helper/index.ts
- houssg/src/helper/ownerFunction.ts
- houssg/src/helper/roomFunction.ts
- houssg/src/store/redux/modalSlice.ts
- houssg/src/types/index.ts
- houssg/src/types/manage.ts
- houssg/src/types/room.ts
- 사업자  리뷰 관련 기능 임시 구현
1 리뷰 확인기능 구현
2 숙소 수정 기능 확인
3 리뷰 추가하기 임시 구현
- 의미없는 css 코드 제거
-  리뷰 수정 함수 생성
- close #238
> [✨ ] Feature/238 owner review  리뷰 관련 임시 기능 구현(백엔드 대기)

- houssg/src/assets/constant/queryKey.ts
- houssg/src/components/usermypages/MyCoupons.tsx
- houssg/src/components/usermypages/MyFavorite.tsx
- houssg/src/components/usermypages/MyPage.tsx
- houssg/src/components/usermypages/MyReview.tsx
- houssg/src/components/usermypages/index.ts
- houssg/src/helper/index.ts
- houssg/src/helper/mypageFunction.ts
- houssg/src/types/index.ts
- houssg/src/types/mypage.ts
- 유저 마이페이지 api 연결 작업
- 나의 후기 api 연결 > useQuery
- 찜한 숙소 api 연결 > useQuery
- #239 
close #239
> [🎨] Feature/239 나의후기찜숙소api연결

- houssg/src/api/api.ts
- houssg/src/assets/constant/queryKey.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/assets/icons/index.ts
- houssg/src/components/reservation/ReservationList.tsx
- houssg/src/pages/user/UserReservationList.tsx
- houssg/src/types/index.ts
- houssg/src/types/reservation.ts
-  500 에러 처리 및 유저 내 예약내역 useQuery로 받기
axios 인스턴스 500에러 처리
예약 내역 데이터 받아오기
예약 내역 타입지정
- close #242
> [✨ ] Feature/242 reserve data naxios 예약 내역 api 연결 및 500에러 통합처리

- houssg/src/components/owner/management/element/RoomCompEdit.tsx
- houssg/src/components/owner/management/element/RoomReviewComp.tsx
- houssg/src/hooks/useFocusRef.ts
- houssg/src/utils/index.ts
- houssg/src/utils/utilFunction.ts
focus 유틸함수, 사장님답변수정구현
- 백엔드 api 변경 => 리뷰 내용 보내주기 가능 --> 구현
-  답글 수정하기 구현
- 포커스 유틸 함수 추가
- close #245
> [✨ ] Focus 유틸함수, 사장님답변수정 구현 

- houssg/src/components/auth/FindPw.tsx
- houssg/src/components/auth/IdFinding.tsx
- houssg/src/components/auth/PwChangeForm.tsx
- houssg/src/components/auth/PwPermitForm.tsx
- houssg/src/components/auth/SignUp.tsx
- houssg/src/helper/authFunction.ts
- houssg/src/store/redux/authSlice.ts
- houssg/src/types/auth.ts
- houssg/src/types/common.ts
- houssg/src/types/index.ts
비밀번호 찾기 추가 및, 아이디 및 회원가입 api 변경사항 반영
- 비밀번호 찾기 추가 및, 아이디 및 회원가입 api 변경사항 반영
- 비밀번호찾기 기능 구현 및 UI 수정
- 비밀번호 찾기시 인증 후 새비밀번호 입력 기능구현
- 중복확인 및 새 비밀번호유효성 검사 추가
- type 수정
- 회원가입 및 id 찾기 바뀐 api 반영 ( 키값)
- close #250
> [:sparkles:] 비밀번호 찾기 추가 및, 아이디 및 회원가입 api 변경사항 반영

- houssg/src/assets/constant/queryKey.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/assets/styles/StyledComponents.ts
- houssg/src/components/owner/management/ManageHouseEdit.tsx
- houssg/src/components/owner/reservation/OwnerCalendar.tsx
- houssg/src/components/owner/reservation/ReservationDropDown.tsx
- houssg/src/components/owner/reservation/index.ts
- houssg/src/helper/index.ts
- houssg/src/helper/ownerFunction.ts
- houssg/src/pages/owner/OwnerReservation.tsx
- houssg/src/store/redux/authSlice.ts
- houssg/src/types/index.ts
- houssg/src/types/ownerReservation.ts
- houssg/src/types/rtk.ts
- 사업자 예약 확인 페이지 api 연결
- 사업자 예약 확인 페이지 api 연결
-  달력 타입지정
-  숙소 상세 정보 줄 바꿈 처리 css
- 로그인 시 alert 처리
- close #247
> [✨ ] Feature/247 ownerreservation 사업자 예약 확인 페이지 api 연결

- houssg/src/components/house/HouseDescription.tsx
- houssg/src/components/house/HouseReview.tsx
- houssg/src/components/owner/reservation/OwnerCalendar.tsx
- houssg/src/components/usermypages/MyFavorite.tsx
- houssg/src/helper/ownerFunction.ts
- houssg/src/pages/owner/OwnerReservation.tsx
- houssg/src/pages/owner/OwnerRoomRegister.tsx
- houssg/src/types/ownerReservation.ts
- houssg/src/utils/index.ts
- houssg/src/utils/utilFunction.ts
- 풀캘린더에 날짜 얻어오기, 관련 함수 + 객실 추가시 keyType에 의한 오류 수정
-  풀캘린더에 날짜 얻어오기, 관련 함수 + 객실 추가시 keyType에 의한 오류 수정
-  객실 추가시 keyType에 의한 오류 수정
-  이전 풀리퀘에서 생긴 빌드에러 해결
-  close #260
> [✨ ] Feature/260 fullcalendar 풀캘린더에 날짜 얻어오기, 관련 함수 + 객실 추가시 keyType에 의한 오류 수정

- houssg/src/components/common/Rating.tsx
- houssg/src/components/house/HouseReview.tsx
- houssg/src/components/house/Review.tsx
- houssg/src/types/houseDetailPage.ts
- houssg/src/utils/hourClock.ts
- 개요
- readonly일 때 평점대로 별 아이콘 안 뜨는 이슈 해결
- 답글 띄우는 코드 추가 ( 답변 없을 때 분기 처리 포함 )
- 공용 함수 hourClock 수정
- 인터페이스 멤버 변수명 오타 수정
- 리뷰탭 css 수정
- close #223
> 💄 Feature/223 유저 숙소상세페이지 리뷰탭

- houssg/src/components/reservation/PaymentWidget.tsx
- houssg/src/components/reservation/ReservationCollapseDetail.tsx
- houssg/src/components/reservation/ReservationList.tsx
- houssg/src/components/reservation/RoomInfo.tsx
- houssg/src/pages/user/UserReservationList.tsx
- houssg/src/types/index.ts
- houssg/src/types/reservation.ts
- 개요
- status가 0인 예약 중인 내역들은 아직 결제 완료 전이라 예약내역에 띄우지 않게 분기처리
- 더미 데이터 삭제
- 분기처리 코드 정리
- css 수정
- 변경 전 ) 콜랩스 데이터 따로 받아오기 : api 코드 작성, 콜랩스 map 돌림 
> 변경 후) 한번에 콜랩스 데이터까지 받아오기 :api 코드 삭제 및 콜랩스 데이터 const로 할당하기, map 돌리는 코드 삭제
- 백 예약 내역 status 변경으로 인한 프론트 분기처리 수정
- css 수정
- api method 변경으로 api 코드 수정
- 인터페이스 업데이트
- close #267
> :lipstick:Feature/267 유저 예약내역 예약상세정보

- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/auth/KaKaoSignUp.tsx
- houssg/src/components/auth/SignUp.tsx
- houssg/src/components/common/CommonModal.tsx
- houssg/src/components/owner/reservation/DateCalModalComp.tsx
- houssg/src/components/owner/reservation/EventCalModalComp.tsx
- houssg/src/components/owner/reservation/element/EventAvailComp.tsx
- houssg/src/hooks/index.ts
- houssg/src/hooks/useKaKaoLogin.ts
- houssg/src/pages/user/UserMain.tsx
- houssg/src/store/redux/authSlice.ts
- houssg/src/utils/isLogin.ts
- 카카오 로그인
1 카카오 로그인
2 카카오 로그인 시 회원가입
3 리덕스로 상태관리
- close #277
> [✨ ] Feature/277 kakao login 카카오 로그인 구현

- houssg/src/assets/constant/queryKey.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/owner/management/ManageHouseEdit.tsx
- houssg/src/components/owner/reservation/OwnerCalendar.tsx
- houssg/src/components/owner/reservation/OwnerReservationModal.tsx
- houssg/src/components/owner/reservation/ReservationDropDown.tsx
- houssg/src/components/owner/reservation/element/DateAvailComp.tsx
- houssg/src/components/owner/reservation/element/EventAvailComp.tsx
- houssg/src/components/owner/reservation/element/EventReserveComp.tsx
- houssg/src/helper/index.ts
- houssg/src/helper/ownerFunction.ts
- houssg/src/hooks/useCalendarStyle.ts
- houssg/src/layout/Header.tsx
- houssg/src/pages/owner/OwnerReservation.tsx
- houssg/src/store/redux/calendarSlice.ts
-  오프라인 예약 및  날짜 클릭시 이용가능 숙소 목록 확인
- 오프라인 예약, 예약성공시 query 무효화, 모달창 오프라인 예약 및 이용가능 숙소 , 불필요 주석 삭제
--> 추후 api 연결 확인(403에러해결) 및 달력 랜더링 문제 해결 
- 불필요 주석 삭제, 달력 첫 렌더링시 불필요한 query 요청 않도록 수정
- close #275
> [✨ ] Feature/275 사업자예약확인3  예약 취소및 이용가능 숙소 상세보기

- houssg/src/components/owner/register/AddressFinder.tsx
- houssg/src/components/owner/register/BusinessRegi.tsx
사업자 등록 로직 리팩토링
- 등록 정보 수정가능하도록
- 등록 정보 수정가능하도록
- close #248
> [:recycle:] 사업자 등록 로직 리팩토링

- houssg/src/components/reservation/BookerInfo.tsx
- houssg/src/components/reservation/Breakdown.tsx
- houssg/src/components/reservation/Calendar.tsx
- houssg/src/components/reservation/PaymentWidget.tsx
- houssg/src/components/reservation/RoomInfo.tsx
- houssg/src/components/reservation/VisitorInfo.tsx
- houssg/src/pages/user/UserReservation.tsx
- 개요
- 예약할 때 포인트 사용시 세션에 포인트도 차감
- 이슈 ( 방문자 폰 번호 받는 input type을 '-'와 같은 문자 입력 못하게 하려고 number로 해서 010 입력시 첫 0이 입력이 안 됨 )
해결 : 타입을 text로 바꾸고 문자 입력 막는 코드를 다른 방법으로 구현
- 폰 번호 입력에 따른 유효성 검사 후 안내해주는 state, visitorAlarm 추가
- 구현한 기능 : 방문자 폰 번호 입력 분기 처리
- 한 핸들러로 방문자 이름이랑 방문자 폰 set 하는 분기 처리
-  ( 예약자와 방문자 동일 체크박스가 있는 상태에서 방문자 이름 입력 시, 방문자 폰번호는 예약자 폰 번호로 남아있는 코드 - 변경 -> )
방문자 이름 입력시, 방문자 폰번호 초기화시키기
- 방문자 폰 번호 입력 시, 숫자가 아닌 문자가 포함되어있다면, set 안 시키고 안내 멘트 노출
- 폰 번호가 0으로 시작 안할 시, set 안 시키고 안내 멘트 노출
- 폰 번호가 11자리 초과이면, set 안 시키고 안내 멘트 노출
- 조건에 맞을 때 폰 번호 입력 시, 폰 번호 set
- 폰 번호 set 할 때, 방문자 이름 초기화 ( 초기화 안 할 시, 예약자와 방문자 동일 체크 박스가 있는 상태면 방문자 이름이 남아있는 이슈가 
있어서 추가한 코드 )
- close #273
> :sparkles: Feature/273 유저 예약하기 이용자핸드폰번호

- houssg/src/assets/constant/queryKey.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/common/CommonModal.tsx
- houssg/src/components/reservation/PaymentWidget.tsx
- houssg/src/components/reservation/Preview.tsx
- houssg/src/components/reservation/ReservationList.tsx
- houssg/src/components/reservation/ReviewWrite.tsx
- houssg/src/helper/index.ts
- houssg/src/helper/userReservationDetailFunction.ts
- houssg/src/types/index.ts
- houssg/src/types/reservation.ts
- 유저 후기 작성 및 보기
- 유저 후기등록
- 유저 후기보기
- #272 
close #272
> [🎨]Feature/272 유저후기작성및보기

- houssg/src/components/owner/reservation/OwnerCalendar.tsx
- houssg/src/components/owner/reservation/element/DateAvailComp.tsx
- houssg/src/components/owner/reservation/element/DateReserveComp.tsx
- houssg/src/components/owner/reservation/element/EventAvailComp.tsx
- houssg/src/components/owner/reservation/element/EventReserveComp.tsx
- houssg/src/helper/ownerFunction.ts
- houssg/src/pages/owner/OwnerManagement.tsx
-  예약보완  예약 취소 키값 오류 수정, 예약 취소성공
-  예약보완  예약 취소 키값 오류 수정, 예약 취소성공
- close #285
> [♻️ ] Feature/285 예약보완  예약 취소 키값 오류 수정, 예약 취소성공

- houssg/src/App.tsx
- houssg/src/api/api.ts
- houssg/src/assets/constant/queryKey.ts
- houssg/src/assets/constant/urlConst.ts
- houssg/src/helper/index.ts
- houssg/src/helper/ownerFunction.ts
- houssg/src/hooks/index.ts
- houssg/src/hooks/useDateStater.tsx
- houssg/src/layout/Header.tsx
- houssg/src/layout/Nav.tsx
- houssg/src/pages/owner/OwnerIncome.tsx
- houssg/src/pages/owner/OwnerMain.tsx
- houssg/src/pages/owner/index.ts
정산내역 데이터 api 연결 및 홈 제거
1 사업자 페이지 홈 제거
2 useQuery로 데이터 받기
- close #281
> [✨ ] Feature/281 sell data  정산내역 데이터 api 연결 및 홈 제거

- houssg/src/assets/constant/routingPath.ts
- houssg/src/layout/Header.tsx
- houssg/src/pages/owner/OwnerIncome.tsx
- houssg/src/pages/owner/OwnerReservation.tsx
- 홈 버튼 route 수정
- 예약 내역 없는 경우 분기 처리
- 정산 내역 날짜 변경 버튼 
- close #296
> [🐛 ] Feature/296 fix 리팩토링 및 미수정된 부분 보완

- houssg/src/components/house/BriefHouse.tsx
- houssg/src/components/house/RoomDetail.tsx
- 개요
- css 수정
- 변경사항
- close #303
> 💄 Feature/303 유저 숙소

- houssg/src/components/common/HeartIcons.tsx
- houssg/src/helper/index.ts
- houssg/src/helper/userHouseDetail.ts
찜하기, 찜 해제 api 함수 파일로 빼서 관리
숙소 상세 페이지 - 찜하기 시, 마이페이지 찜한 숙소 쿼리 키 mutation 걸기
- 개요
- 찜하기, 찜 해제 api 함수 파일로 빼서 관리
숙소 상세 페이지 - 찜하기 시, 마이페이지 찜한 숙소 쿼리 키 mutation 걸기
- 변경사항
- close #306
> [:art:] 306 - 찜

- houssg/src/assets/constant/urlConst.ts
- houssg/src/components/house/HouseInfo.tsx
- houssg/src/components/owner/management/ManageRoomWrap.tsx
- houssg/src/components/reservation/ReservationList.tsx
- houssg/src/helper/ownerFunction.ts
- houssg/src/pages/owner/OwnerManagement.tsx
- houssg/src/pages/user/UserHouseDetail.tsx
- houssg/src/types/room.ts
> [🐛 ] Feature/308 bugfix 버그 픽스

- houssg/src/components/owner/management/ManageReview.tsx
- houssg/src/components/reservation/ReviewWrite.tsx
- houssg/src/helper/authFunction.ts
- houssg/src/helper/userReservationDetailFunction.ts
- houssg/src/pages/owner/OwnerIncome.tsx
- houssg/src/pages/owner/OwnerReservation.tsx
-  정산내역 오름차순 정렬+ 불필요 콘솔제거
-  정산내역 오름차순 정렬+ 불필요 콘솔제거
- close #318
> [♻️ ] Feature/318 fixincome  정산내역 오름차순 정렬+ 불필요 콘솔제거

- houssg/src/components/house/Review.tsx
- 개요
- 리뷰 이미지 여부에 따른 이미지:댓글 내용 가로 넓이 비율 분기처리
- 변경사항
- close #323
> 💄 Feature/323 숙소상세페이지 댓글

- houssg/src/components/reservation/Breakdown.tsx
- 개요
- 변경 전 ) 포인트 입력 시, 안내 문구 종류를 state관리하여 컴포넌트 return문에서 state를 분기처리해서 state에 따른 문구 출력
이슈 ) 그냥 문구 종류가 아닌 문구를 state로 관리하면 되는데 과정을 한번 더 불필요하게 거침
변경 후 ) 문구를 state로 관리하여 문구 여부에 따라 문구 출력 분기처리하고 state를 바로 출력시킴
- 변경 전 ) 할인가 > 상품 금액 일 때, 쿠폰, 포인트 입력은 가능하고 예약하기 버튼만 막아놨음
이슈 ) 어차피 할인가 > 상품 금액이라 예약이 불가능한데 할인 정보 입력받을 때부터 막지 않고 다 입력받고 이후에 알려주기에 UX가 불편하고 , 마이너스 결제액을 보여주는 것도 UX를 해침
변경 후 ) 쿠폰 선택과 포인트 입력할 때마다 할인가 > 상품 금액 을 체크하여 바로 바로 분기처리
- 변경사항
- close #326
> :bug:Feature/326 예약하기 ux

- houssg/src/assets/styles/theme.ts
- houssg/src/components/auth/AuthWrap.tsx
- houssg/src/components/auth/FindId.tsx
- houssg/src/components/auth/FindPw.tsx
- houssg/src/components/auth/PwChangeForm.tsx
- houssg/src/components/auth/PwPermitForm.tsx
- houssg/src/components/auth/SignUp.tsx
- houssg/src/components/auth/element/AuthInput.tsx
- houssg/src/components/auth/element/AuthModeBtn.tsx
- houssg/src/components/auth/element/AuthSubmitBtn.tsx
- houssg/src/components/common/CommonInstruction.tsx
- houssg/src/components/common/KakaoMap.tsx
- houssg/src/components/house/RoomList.tsx
- houssg/src/components/owner/management/ManageHouseEdit.tsx
- houssg/src/components/owner/management/ManageNav.tsx
- houssg/src/components/owner/management/ManageRoomWrap.tsx
- houssg/src/components/owner/management/ManageTabComp.tsx
- houssg/src/components/owner/management/ManageWrapComp.tsx
- houssg/src/components/owner/register/AddressFinder.tsx
- houssg/src/components/owner/register/BusinessRegi.tsx
- houssg/src/components/userhouselist/HouseList.tsx
- houssg/src/components/usermain/BannerSlider.tsx
- houssg/src/components/usermain/HomeSlider.tsx
- houssg/src/components/usermypages/EditNickName.tsx
- houssg/src/components/usermypages/EditPassword.tsx
- houssg/src/components/usermypages/EditPhoneNumber.tsx
- houssg/src/types/houseDetailPage.ts
- houssg/src/types/index.ts
- houssg/src/types/user.ts
- 임포트 순서 수정+ barrel 미적용 수정
- 임포트 순서 수정+ barrel 미적용 수정
- close #328
> [:art:] 임포트 순서 수정+ barrel 미적용 수정

- houssg/src/components/reservation/Breakdown.tsx
- 개요
- 할인가 >원가 일 때 에러 문구가 뜨고, 원가 < 할인가인 포인트를 입력해도 에러 문구가 안 사라지는 이슈 해결
- 변경사항
- 이슈번호
> :bug: Feature/330 예약하기 디버깅
